#============================================
#          Configs for Docker:
#============================================

#Datasourse props
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/bike_championship?useUnicode=true&characterEncoding=utf8&useSSL=false&verifyServerCertificate=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop

#Jwt properties
jwt:
  secret: JWTSuperSecretKey
  expirationInMs: 604800000

#Cors constants
cors:
  origin: "http://localhost:3000"